### ISSUE TITLE
Blender 4.0.1 crashing when baking with Image (Plane)

### ISSUE THREAD

**Issue by Poucy113** [avelgest/baker-node#2]
Blender crashes (segmentation fault) when baking an image as plane

You also can't re-open the file after blender crashed, the file is "corrupted" forever

[system-info.txt](https://github.com/avelgest/baker-node/files/13697072/system-info.txt)
[blender.crash.txt](https://github.com/avelgest/baker-node/files/13697075/blender.crash.txt)

Blender 4.0.1 and baker-node v0.8.2

**Comment by Poucy113** [comment]
Update !

Is seems like this only happens when the Baker's node input has no vector/coordinate input.

In this case the bake works and blender does not crash:
![image](https://github.com/avelgest/baker-node/assets/66266372/b7cbcf4d-0474-4313-b7c0-7f06abbce0ec)

In this case it also works:
![image](https://github.com/avelgest/baker-node/assets/66266372/42930ce6-091b-4a6e-9142-13169bc5fefd)
Same for this:
![image](https://github.com/avelgest/baker-node/assets/66266372/cebaade7-4157-4569-9a29-750ac8fe97ed)

In this case not:
![image](https://github.com/avelgest/baker-node/assets/66266372/7a50045b-c543-4dfc-b0b3-0a7bb9a1a6d8)
It seems Mapping nodes break everyting

**Comment by avelgest** [comment]
Thanks for the detailed issue!
I haven't been able to reproduce any consistent crashes, but have reproduced occasional crashes when using *Image (Plane)* which are due to the temporary plane created for baking being deleted too early.

I've pushed commit [dcc2373](https://github.com/avelgest/baker-node/commit/dcc2373b5a9f1c990fdd417a3ca151e77e352e13) to main which should fix the crashes described above and hopefully fix the crashes that you're experiencing as well (not sure about the differences between node setups, but prehaps certain setups manage to finish reading the temporary plane's data before the plane is deleted).
If the crashes persist could you try disabling **Bake in Background** in the add-on's preferences and seeing it changes anything?

**Comment by Poucy113** [comment]
Still on **v0.8.2**, i disabled "Bake in background" and now there isn't any issue while baking as Image(Plane)
![image](https://github.com/avelgest/baker-node/assets/66266372/d5882f84-9cb9-42d2-96d1-22a37eb0cf97)

With the new commit `dc2373` it also works with "Bake in background" enabled

Thanks 👍
